### ISSUE TITLE
Integrierung von Pull Request 1

### ISSUE THREAD

**Issue by MarieT1D** [Benecoder/Schafskopf-Bot-API#2]
Der Code, den ich in PR 1 erstellt habe, muss auch noch in den restlichen Code besser integriert werden.

**Comment by Benecoder** [comment]
Bin einmal drüber gegangen und habe alle hardgecodeten ID references erneuert.

**Comment by Benecoder** [comment]
Jetzt ist zu mindest alles korrigiert. Die Frage ist ob man das alles jetzt auch noch Tiefer integrieren will. Würde glaube ich minimal die Performance einschränken aber die Leserlichkeit verbessern.
